### ISSUE TITLE
has this been tested on postgreSql databases

### ISSUE THREAD

**Issue by danmarsden** [bfh/moodle-mod_verbalfeedback#10]
the function verbalfeedback_get_user_grades looks to me like it might not run in a PostGres based db - might be some missing group by fields in there?

Note - supporting both mysql and postgres is a requirement for the plugins db.

**Comment by lucaboesch** [comment]
Yes, Dan, I do develop in a PostgreSQL based development environment and I can report back that there were no issues whatsoever.

**Comment by lucaboesch** [comment]
There is now a PHPUnit test running that function.
