### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by miguelalbano** [bfh/moodle-mod_verbalfeedback#28]
Not sure if this is the right place to report it, but trying to install the latest version on a recent Moodle installation and I'm coming across an error installing this plugin. So far, the only one giving me an error (as attached).

![image](https://user-images.githubusercontent.com/30835922/197588138-5f34e0a6-4fc8-4ee3-aafc-1f7833f52a30.png)

It didn't throw any red flags in the previous steps, so I'm just trying to understand if I'm missing anything in terms of requirements.

**Comment by lucaboesch** [comment]
Verbal feedback has been improved.
Please comment if you are still experiencing this.
Closing in the meantime.
